dist: xenial # Ubuntu 16.04
language: node_js
node_js:
  - 10

before_install:
  - 'sudo apt-get install jq'

  - staging_token=$(curl -X POST -d "{\"username\":\"$domain_api_username_staging\",\"password\":\"$domain_api_password_staging\"}" $domain_api_url_staging/auth | jq '.accessToken' | tr -d '"')
  - 'curl -H "Authorization: $staging_token" $domain_api_url_staging/get-terraform-domains > sites-staging.json'
  - 'curl -H "Authorization: $staging_token" $domain_api_url_staging/get-terraform-domain-records > records-staging.json'
  - cat sites-staging.json | jq '.code'
  - cat records-staging.json | jq '.code'
  - cat sites-staging.json | jq '.code == null'
  - cat records-staging.json | jq '.code == null'

  - production_token=$(curl -X POST -d "{\"username\":\"$domain_api_username_production\",\"password\":\"$domain_api_password_production\"}" $domain_api_url_production/auth | jq '.accessToken' | tr -d '"')
  - 'curl -H "Authorization: $production_token" $domain_api_url_production/get-terraform-domains1 > sites-production.json'
  - 'curl -H "Authorization: $production_token" $domain_api_url_production/domains/bf3740c2-6980-4e52-9d32-cb1a5bfb6d14no > records-production.json'
  - cat sites-production.json | jq '.code'
  - cat records-production.json | jq '.code'
  - cat sites-production.json | jq '.code'
  - cat records-production.json | jq '.code'
  - cat sites-production.json | jq '.code == null'
  - cat records-production.json | jq '.code == null'

jobs:
  include:
    - stage: terraform plan
      if: type = push AND branch = main
      script:
        - echo $staging_token
        - echo $production_token
        - cat sites-staging.json | jq '.'
        - cat records-staging.json | jq '.'
        - cat sites-production.json | jq '.'
        - cat records-production.json | jq '.'