dist: xenial # Ubuntu 16.04
language: node_js
node_js:
  - 10

before_install:
  - 'sudo apt-get install jq'
  - staging_token=$(curl -X POST -d "{\"username\":\"milk_portal\",\"password\":\"milk_portal@1234569\"}" https://staging-mb-api-domains.milkbox.systems/auth | jq '.accessToken')
  - 'curl -H "Authorization: $staging_token" https://staging-mb-api-domains.milkbox.systems/get-terraform-domains'

jobs:
  include:
    - stage: terraform plan
      if: type = push AND branch = main
      script:
        - echo $staging_token