dist: xenial # Ubuntu 16.04
language: node_js
node_js:
  - 10

before_install:
  - 'sudo apt-get install jq'
  - staging_token=$(curl -X POST -d "{\"username\":\"$domain_api_username_staging\",\"password\":\"$domain_api_password_staging\"}" $domain_api_url_staging/auth | jq '.accessToken')
  - 'curl -H "Authorization: $staging_token" https://staging-mb-api-domains.milkbox.systems/get-terraform-domains > sites-staging.json'
  - 'curl -H "Authorization: $staging_token" https://staging-mb-api-domains.milkbox.systems/get-terraform-domain-records > records-staging.json'

jobs:
  include:
    - stage: terraform plan
      if: type = push AND branch = main
      script:
        - echo $staging_token
        - cat sites-staging.json | jq '.'
        - cat records-staging.json | jq '.'